version: '3'

services:
  rtd-ml:
    build: ./rtd-ml
    volumes:
      - ./rtd-ml:/usr/src/app
    ports: 
      - "5000:5000"

  rtd-backend:
    build: ./rtd-backend
    volumes:
      - ./rtd-backend:/usr/src/app
    ports: 
      - "8080:8080"
    depends_on:
      - rtd-ml

  rtd-ui:
    build: ./rtd-ui
    volumes:
      - ./rtd-ui:/usr/src/app
    ports: 
      - "3000:80"
    depends_on:
      - rtd-backend